# Generated by Django 4.2.11 on 2026-05-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_teacher_profile_complete"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Main Campus", max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="School latitude coordinate",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="School longitude coordinate",
                        max_digits=9,
                    ),
                ),
                (
                    "allowed_radius",
                    models.PositiveIntegerField(
                        default=100, help_text="Allowed radius in meters"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Location",
                "verbose_name_plural": "School Locations",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("attendance", "Attendance"),
                    ("schedule", "Schedule"),
                    ("reminder", "Class Reminder"),
                    ("general", "General"),
                    ("admin", "Admin Notice"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="label",
            field=models.CharField(default="School Attendance QR", max_length=100),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="course_type",
            field=models.CharField(
                choices=[("core", "Core Subjects"), ("departmental", "Departmental")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="course_type",
            field=models.CharField(
                blank=True,
                choices=[("core", "Core Subjects"), ("departmental", "Departmental")],
                max_length=20,
            ),
        ),
    ]
