from django.urls import path
from . import views

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('sw.js', views.service_worker, name='service_worker'),
    path('offline/', views.offline_page, name='offline'),
    path('login/', views.unified_login, name='login'),
    path('login/', views.unified_login, name='teacher_login'),
    path('register/', views.teacher_register, name='teacher_register'),
    path('admin-portal/', views.unified_login, name='admin_login'),
    path('superadmin-portal/', views.superadmin_login, name='superadmin_login'),
    path('logout/', views.logout_view, name='logout'),
    path('teacher/dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('teacher/complete-profile/', views.teacher_complete_profile, name='teacher_complete_profile'),
    path('teacher/update-profile/', views.teacher_update_profile, name='teacher_update_profile'),
    path('teacher/change-password/', views.teacher_change_password, name='teacher_change_password'),
    path('teacher/notification/<int:notif_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('teacher/timetable/', views.view_timetable, name='view_timetable'),
    path('teacher/qr-scanner/', views.qr_scanner, name='qr_scanner'),
    path('scan/school/<uuid:qr_uuid>/', views.scan_school_qr, name='scan_school_qr'),
    path('scan/lesson/<uuid:qr_uuid>/', views.scan_lesson_qr, name='scan_lesson_qr'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/teachers/', views.admin_teachers, name='admin_teachers'),
    path('admin-dashboard/teachers/<int:teacher_id>/', views.teacher_detail, name='teacher_detail'),
    path('admin-dashboard/teachers/<int:teacher_id>/approve/', views.approve_teacher, name='approve_teacher'),
    path('admin-dashboard/teachers/<int:teacher_id>/reject/', views.reject_teacher, name='reject_teacher'),
    path('admin-dashboard/teachers/<int:teacher_id>/delete/', views.delete_teacher, name='delete_teacher'),
    path('admin-dashboard/department/<str:dept_slug>/', views.admin_department_view, name='admin_department_view'),
    path('admin-dashboard/attendance/', views.admin_attendance, name='admin_attendance'),
    path('admin-dashboard/timetable/', views.admin_timetable, name='admin_timetable'),
    path('admin-dashboard/timetable/<int:entry_id>/delete/', views.delete_timetable_entry, name='delete_timetable_entry'),
    path('admin-dashboard/schedule/', views.admin_schedule, name='admin_schedule'),
    path('admin-dashboard/notifications/', views.admin_notifications, name='admin_notifications'),
    path('admin-dashboard/create-teacher/', views.admin_create_teacher, name='admin_create_teacher'),
    # QR view only for admin (no generation)
    path('admin-dashboard/qr/', views.admin_qr_view, name='admin_qr_view'),
    path('admin-dashboard/qr/<int:qr_id>/', views.qr_detail, name='qr_detail'),
    # Super admin QR generation
    path('superadmin/qr/', views.generate_qr, name='generate_qr'),
    path('superadmin/qr/<int:qr_id>/', views.qr_detail_sa, name='qr_detail_sa'),
    path('api/notifications/', views.get_notifications_api, name='notifications_api'),
    path('api/schedule-reminders/', views.get_schedule_reminders_api, name='schedule_reminders_api'),
    path('api/schedule/<int:schedule_id>/complete/', views.mark_schedule_complete, name='mark_schedule_complete'),
    path('superadmin/', views.superadmin_dashboard, name='superadmin_dashboard'),
    path('superadmin/admins/', views.superadmin_admins, name='superadmin_admins'),
    path('superadmin/create-admin/', views.superadmin_create_admin, name='superadmin_create_admin'),
    path('superadmin/delete-admin/<int:admin_id>/', views.superadmin_delete_admin, name='superadmin_delete_admin'),
    path('superadmin/teachers/', views.superadmin_teachers, name='superadmin_teachers'),
    path('superadmin/teachers/<int:teacher_id>/approve/', views.superadmin_approve_teacher, name='superadmin_approve_teacher'),
    path('superadmin/teachers/<int:teacher_id>/delete/', views.superadmin_delete_teacher, name='superadmin_delete_teacher'),
    path('superadmin/change-credentials/', views.superadmin_change_credentials, name='superadmin_change_credentials'),
    path('superadmin/staff-ids/', views.superadmin_staff_ids, name='superadmin_staff_ids'),
]
